loss calculation + plotting loss and accuracy
hubert-groen/ZZSN_KnowledgeDistillation pull request #1
Opened 2024-05-08 10:46 UTC by hubert-groen

2024-05-08 20:36 UTC, WojciechGierulski requested changes

2024-05-08 20:36 UTC, WojciechGierulski commented on resnet.py
> +            test_dataset.targets = teacher_logits
tu chyba full_dataset?

2024-05-08 20:36 UTC, WojciechGierulski commented on resnet.py
> +        train_subset = Subset(full_dataset, train_idx)
daj tu pls test_idx nazwę zmiennej

2024-05-08 20:36 UTC, WojciechGierulski commented on resnet.py
> +                total_loss += loss.item() * images.size(0)
czemu `* images.size(0)`?

2024-05-08 20:36 UTC, WojciechGierulski commented on resnet.py
> +        average_loss = total_loss / total
tutaj raczej trzeba podzielić przez liczbę batchy, a nie próbek treningowych

2024-05-09 14:24 UTC, hubert-groen commented on resnet.py
> +            test_dataset.targets = teacher_logits
Dziwne, na moim branchu jest full_dataset tutaj. Zobaczę jak będzie po merge.

2024-05-09 14:28 UTC, hubert-groen commented on resnet.py
> +        train_subset = Subset(full_dataset, train_idx)
Ok

2024-05-09 14:30 UTC, hubert-groen commented on resnet.py
> +                total_loss += loss.item() * images.size(0)
Usuwam

2024-05-09 14:31 UTC, hubert-groen commented on resnet.py
> +        average_loss = total_loss / total
OK, robię / batch_size

2024-05-09 14:32 UTC, closed without merging